version: '3'
services:
  redis-service:
    build:
      context: .
      dockerfile: Dockerfile-redis
    ports:
      - "6379:6379"  
    networks:
      - mybennetwork
    container_name: redisben-app
    volumes:
      - ./redis:/code/redis
      - ./redis/requirements.txt:/code/redis/requirements.txt
    restart: on-failure

  home-service:
    build:
      context: .
      dockerfile: Dockerfile-home
    ports:
      - "8080:80"   
    networks:
      - mybennetwork
    container_name: myapp-app
    volumes:
      - ./home:/code/home
      - ./home/requirements.txt:/code/home/requirements.txt
    restart: on-failure

  app-service:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "80:80"
    networks:
      - mybennetwork
    container_name: appben-app
    volumes:
      - ./app:/code/app
      - ./app/requirements.txt:/code/app/requirements.txt
    restart: on-failure

networks:
  mybennetwork:
